// examples/vue-example/pages/home.vue
<script setup lang="ts">
import { ref } from 'vue'

// console.debug('renderProps', props)

// biome-ignore lint/correctness/noUnusedVariables: any
const count = ref(0)
</script>

<template>
  <main>
    <div>hello world</div>
    <div>
      <a href="/a">goto /a</a>
      <router-link to="/blog">
        goto /blog
      </router-link>
    </div>
    <button type="button" @click="count++">
      count is {{ count }}
    </button>
  </main>
</template>

// examples/react-example/remote-template/pages/home.tsx
import { useState } from 'react'
import { Link } from 'react-router'
import { getComp } from '../component-register'
import styles from './home.module.css'

export function Home(): React.ReactElement {
  const [count, setCount] = useState(0)

  const Button = getComp('SchemaButton') || 'button'

  // console.debug('renderContext', renderContext)

  return (
    <main>
      <div className={styles.title}>hello world</div>
      <div>
        <a href="/b/vue">goto /b</a>
        <Link to="/blog">goto /blog</Link>
      </div>
      <Button onClick={() => setCount(count + 1)}>
        count is
        {count}
      </Button>
    </main>
  )
}
